---
- name: Include variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ landscape_version }}.yml'
        - main.yml
      paths:
        - 'vars'

- name: Include check tasks
  ansible.builtin.include_tasks: check.yml
  tags: check

- name: Include prepare tasks
  ansible.builtin.include_tasks: prepare.yml
  tags: prepare

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  tags: install
